//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTin
    {
        public int id { get; set; }
        public string ten { get; set; }
        public Nullable<int> hienTai { get; set; }
        public Nullable<int> congSuatLonNhat { get; set; }
        public Nullable<int> thietKe { get; set; }
        public Nullable<int> sanLuongNgay { get; set; }
        public Nullable<System.DateTime> time { get; set; }
    }
}
